create database algafood;

DROP TABLE TAB_REST_FORM_PAG CASCADE CONSTRAINTS;
DROP TABLE TAB_FORMAPAGAMENTO CASCADE CONSTRAINTS;
DROP TABLE TAB_COZINHA CASCADE CONSTRAINTS;
DROP TABLE TAB_RESTAURANTE CASCADE CONSTRAINTS;
DROP TABLE TAB_PERMISSAO CASCADE CONSTRAINTS;
DROP TABLE TAB_ESTADO CASCADE CONSTRAINTS;
DROP TABLE TAB_CIDADE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_TAB_RESTAURANTE;
DROP SEQUENCE SEQ_TAB_COZINHA;
DROP SEQUENCE SEQ_TAB_FORMAPAGAMENTO;
DROP SEQUENCE SEQ_TAB_REST_FORM_PAG;
DROP SEQUENCE SEQ_TAB_PERMISSAO;
DROP SEQUENCE SEQ_TAB_ESTADO;
DROP SEQUENCE SEQ_TAB_CIDADE;

CREATE SEQUENCE SEQ_TAB_RESTAURANTE INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_COZINHA INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_FORMAPAGAMENTO INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_REST_FORM_PAG INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_PERMISSAO INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_ESTADO INCREMENT BY 1 MAXVALUE 99999999;
CREATE SEQUENCE SEQ_TAB_CIDADE INCREMENT BY 1 MAXVALUE 99999999;

CREATE TABLE TAB_COZINHA (
    ID_COZINHA SERIAL PRIMARY KEY,
    NM_COZINHA VARCHAR(255) NOT NULL);

comment on table TAB_COZINHA is 'Tabela que armazena as informações sobre a cozinha';
comment on column TAB_COZINHA.ID_COZINHA is 'Identificador da tabela cozinha';
comment on column TAB_COZINHA.NM_COZINHA is 'Nome da especialidade da cozinha';

CREATE TABLE TAB_RESTAURANTE (
    ID_RESTAURANTE SERIAL PRIMARY KEY,
    NM_RESTAURANTE VARCHAR(255) NOT NULL,
    TAXA_FRETE DECIMAL,
    ID_COZINHA BIGINT not null,
    CONSTRAINT FK_COZINHA FOREIGN KEY(ID_COZINHA) REFERENCES TAB_COZINHA(ID_COZINHA));

comment on table TAB_RESTAURANTE is 'Tabela que armazena as informações dos restaurantes';
comment on column TAB_RESTAURANTE.ID_RESTAURANTE is 'Identificador da tabela de restaurante';
comment on column TAB_RESTAURANTE.NM_RESTAURANTE is 'Nome do restaurante';
comment on column TAB_RESTAURANTE.TAXA_FRETE is 'taxa do frete que o restaurante possui';
comment on column TAB_RESTAURANTE.ID_COZINHA is 'Identificador do relacionamento com a tabela cozinha';


CREATE TABLE TAB_FORMAPAGAMENTO (
    ID_FORMAPAGAMENTO SERIAL PRIMARY KEY,
    DS_FORMAPAGAMENTO VARCHAR(255) NOT NULL);

comment on table TAB_FORMAPAGAMENTO is 'Tabela que armazena as formas de pagamento';
comment on column TAB_FORMAPAGAMENTO.ID_FORMAPAGAMENTO is 'Identificador da tabela de formapagamento';
comment on column TAB_FORMAPAGAMENTO.DS_FORMAPAGAMENTO is 'Descrição da forma de pagamento';


CREATE TABLE TAB_REST_FORM_PAG (
    ID_REST_FORM_PAG SERIAL PRIMARY KEY,
    ID_RESTAURANTE BIGINT NOT NULL,
    ID_FORMAPAGAMENTO BIGINT NOT NULL,
    CONSTRAINT FK_RESTAURANTE FOREIGN KEY(ID_RESTAURANTE) REFERENCES TAB_RESTAURANTE(ID_RESTAURANTE),
    CONSTRAINT FK_FORMAPAGAMENTO FOREIGN KEY(ID_FORMAPAGAMENTO) REFERENCES TAB_FORMAPAGAMENTO(ID_FORMAPAGAMENTO),
    CONSTRAINT UK_REST_FORM_PAG UNIQUE (ID_REST_FORM_PAG, ID_RESTAURANTE, ID_FORMAPAGAMENTO));

comment on table TAB_REST_FORM_PAG is 'Tabela que armazena o relacionamento entre o Restaurante e as formas de pagamento';
comment on column TAB_REST_FORM_PAG.ID_REST_FORM_PAG is 'Identificador da tabela de restformpag';
comment on column TAB_REST_FORM_PAG.ID_RESTAURANTE is 'Descrição da forma de pagamento';
comment on column TAB_REST_FORM_PAG.ID_FORMAPAGAMENTO is 'Descrição da forma de pagamento';

CREATE TABLE TAB_PERMISSAO (
    ID_PERMISSAO SERIAL PRIMARY KEY,
    NM_PERMISSAO VARCHAR(255) NOT NULL,
    DS_PERMISSAO VARCHAR(255) NOT NULL);

comment on table TAB_PERMISSAO is 'Tabela que informa a permissao de usuarios';
comment on column TAB_PERMISSAO.ID_PERMISSAO is 'Identificador da tabela de permissao';
comment on column TAB_PERMISSAO.NM_PERMISSAO is 'Nome que sera apresentado a permissao';
comment on column TAB_PERMISSAO.DS_PERMISSAO is 'Descrição detalhada da permissao';

CREATE TABLE TAB_ESTADO (
    ID_ESTADO SERIAL PRIMARY KEY,
    NM_ESTADO VARCHAR(255) NOT NULL);

comment on table TAB_ESTADO is 'Tabela que registra o estado de origin do retaurante';
comment on column TAB_ESTADO.ID_ESTADO is 'Identificador da tabela de estado';
comment on column TAB_ESTADO.NM_ESTADO is 'Nome do estado';


CREATE TABLE TAB_CIDADE (
    ID_CIDADE SERIAL PRIMARY KEY,
    NM_CIDADE VARCHAR(255) NOT NULL,
    ID_ESTADO BIGINT not null,
    CONSTRAINT FK_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES TAB_ESTADO(ID_ESTADO));

comment on table TAB_CIDADE is 'Tabela que armazena cidade';
comment on column TAB_CIDADE.ID_CIDADE is 'Identificador da tabela cidade';
comment on column TAB_CIDADE.NM_CIDADE is 'Nome da cidade';
comment on column TAB_CIDADE.ID_ESTADO is 'Identificador do relacionamento com a tabela estado';