server:
  port: 8090

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: root

  jpa:
    show-sql: true
